DRECK_BLENDER_OUTPUT_TYPE_SCRIPT_PATHS += $(patsubst ./%.blend, ./plugins/blender/generated/%.ts, $(DRECK_BLENDER_INPUT_BLEND_PATHS))

DRECK_GENERATED_PATHS += $(DRECK_BLENDER_OUTPUT_TYPE_SCRIPT_PATHS)
