/**
 * Calculates a world transformation matrix matching that which would be generated by Blender in XYZ Euler mode.
 * @param locationX The location of the object on the X axis.
 * @param locationY The location of the object on the Y axis.
 * @param locationZ The location of the object on the Z axis.
 * @param rotationX The rotation of the object around the X axis, in radians.
 * @param rotationY The rotation of the object around the Y axis, in radians.
 * @param rotationZ The rotation of the object around the Z axis, in radians.
 * @param scaleX The scale of the object on the X axis, as a multiplying factor.
 * @param scaleY The scale of the object on the Y axis, as a multiplying factor.
 * @param scaleZ The scale of the object on the Z axis, as a multiplying factor.
 * @param matrix The matrix to which to write the result.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function blenderCalculateTransform(
  locationX: number,
  locationY: number,
  locationZ: number,
  rotationX: number,
  rotationY: number,
  rotationZ: number,
  scaleX: number,
  scaleY: number,
  scaleZ: number,
  matrix: BlenderMatrix
): void {
  const sinX = Math.sin(rotationX);
  const cosX = Math.cos(rotationX);

  const a0 = scaleY * cosX;
  const a1 = -scaleZ * sinX;
  const a2 = scaleY * sinX;
  const a3 = scaleZ * cosX;

  const sinY = Math.sin(rotationY);
  const cosY = Math.cos(rotationY);

  const b0 = scaleX * cosY;
  const b1 = a2 * sinY;
  const b2 = a3 * sinY;

  const sinZ = Math.sin(rotationZ);
  const cosZ = Math.cos(rotationZ);

  matrix[0] = b0 * cosZ;
  matrix[1] = b1 * cosZ - a0 * sinZ;
  matrix[2] = b2 * cosZ - a1 * sinZ;
  matrix[3] = locationX;
  matrix[4] = b0 * sinZ;
  matrix[5] = a0 * cosZ + b1 * sinZ;
  matrix[6] = a1 * cosZ + b2 * sinZ;
  matrix[7] = locationY;
  matrix[8] = -scaleX * sinY;
  matrix[9] = a2 * cosY;
  matrix[10] = a3 * cosY;
  matrix[11] = locationZ;
  matrix[12] = 0;
  matrix[13] = 0;
  matrix[14] = 0;
  matrix[15] = 1;
}
